### PR TITLE
XLS 85d: Token Escrow

### LINKED ISSUE #3026: EscrowCreate doesn’t support MPToken or IOU amounts despite ledger capability
# Summary:
Although the XRP Ledger now supports escrows for trustline tokens and Multi‑purpose Tokens (MPT), the EscrowCreate type in xrpl.js still limits Amount to XRP only, blocking non‑XRP escrow functionality.

---- 

## 🔍 Context & Problem
- The TokenEscrow amendment (XLS‑85) extends ledger escrow support to issued tokens (IOUs) and MPTs—not just XRP  ￼ ￼ ￼.
- MPTs also support escrow via the tfMPTCanEscrow flag, allowing holders to lock balances into an escrow via EscrowCreate/EscrowFinish  ￼.
- However, the EscrowCreate model in xrpl.js hardcodes:

```
Amount: string
```

representing XRP drops only  ￼, making Amount incompatible with token-style objects.

---- 

## 🧪 Steps to Reproduce
	1.	Import and try to construct an EscrowCreate transaction with a token amount object:

```typescript
const tx: EscrowCreate = {
  TransactionType: "EscrowCreate",
  Account: "...",
  Amount: { currency: "USD", issuer: "...", value: "100" },  // or MPT style
  Destination: "...",
  FinishAfter: ...
}
```

	2.	TypeScript throws an error: Type '{ currency: string; issuer: string; value: string; }' is not assignable to type 'string'.
	3.	Even if bypassed via casting, the library structures it as an XRP-only amount in submit() or sign() routines, causing a protocol error.

## ✅ Expected Behavior

With TokenEscrow and MPT amendments active, xrpl.js should allow:
- Amount as either:
	- XRP amount (string)
	- Token object { currency, issuer, value }
	- MPT object { mpt_issuance_id, value }
- Proper serialization of token escrows to JSON matching ledger spec—similar to Payment, OfferCreate, and AMMCreate updated in XLS‑85.

⸻

I’d be happy to help with a PR to update the interface and serialization logic if this aligns with the library roadmap!

⸻

Let me know if you’d like help sketching out the code changes or tests.

### PR DESCRIPTION
**Pull request by ckeshava**
## High Level Overview of Change
This PR implements support for Token-Escrow in xrpl.js library.

The XLS specification can be found [here](https://github.com/XRPLF/XRPL-Standards/tree/master/XLS-0085d-token-escrow).
[This is the C++ implementation](https://github.com/XRPLF/rippled/pull/5185) of the Token-Escrow feature.

### Context of Change

This PR enables developers to use IOUs and MPTs with the Escrow functionality. This PR will also fix #3026 

### Type of Change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Refactor (non-breaking change that only restructures code)
- [ ] Tests (You added tests for code that already exists, or your new feature included in this PR)
- [ ] Documentation Updates
- [ ] Release

### Did you update HISTORY.md?

- [x] Yes
- [ ] No, this change does not impact library users

## Test Plan

Relevant unit and integration tests have been included.

### CODE REVIEW

File: packages/xrpl/src/models/ledger/MPTokenIssuance.ts [hunk 1]
```diff
@@ -10,4 +10,7 @@ export interface MPTokenIssuance extends BaseLedgerEntry, HasPreviousTxnID {
   TransferFee?: number
   MPTokenMetadata?: string
   OwnerNode?: string
+
+  // (Optional) The total of all outstanding escrows for this issuance.
+  LockedAmount?: number
 }
```
[the remark this answers is not in the document]
Comment (ckeshava) [reply packages/xrpl/src/models/ledger/MPTokenIssuance.ts]: This was a design decision taken across multiple products of the XRPL eco-system. I can't change it unilaterally

**Review by RomThpt — APPROVED** [review]
Looks great !

File: packages/xrpl/HISTORY.md [hunk 2]
```diff
@@ -7,6 +7,9 @@ Subscribe to [the **xrpl-announce** mailing list](https://groups.google.com/g/xr
 ### Fixed
 * Fix `AccountRoot` ledger object to correctly parse `FirstNFTokenSequence` field.
 
+### Added
+* Implement support for XLS-85d Token Escrow amendment.
+
```
Comment (mvadari) [inline packages/xrpl/HISTORY.md]: nit: `Added` should go above `Fixed`

File: packages/xrpl/src/models/ledger/MPToken.ts [hunk 3]
```diff
@@ -8,4 +8,7 @@ export interface MPToken extends BaseLedgerEntry, HasPreviousTxnID {
   MPTAmount?: MPTAmount
   Flags: number
   OwnerNode?: string
+
+  // (Optional) The total of all outstanding escrows for this issuance.
```
Comment (mvadari) [inline packages/xrpl/src/models/ledger/MPToken.ts]:
```suggestion
  OwnerNode?: string

  // The total of all outstanding escrows for this issuance.
```

File: packages/xrpl/src/models/ledger/MPTokenIssuance.ts [hunk 4]
```diff
@@ -10,4 +10,7 @@ export interface MPTokenIssuance extends BaseLedgerEntry, HasPreviousTxnID {
   TransferFee?: number
   MPTokenMetadata?: string
   OwnerNode?: string
+
+  // (Optional) The total of all outstanding escrows for this issuance.
```
Comment (mvadari) [inline packages/xrpl/src/models/ledger/MPTokenIssuance.ts]:
```suggestion
  // The total of all outstanding escrows for this issuance.
```

File: packages/xrpl/HISTORY.md (hunk 2 above)
Comment (ckeshava) [reply packages/xrpl/HISTORY.md]: Why? How does the order matter? :)

Comment (mvadari) [reply packages/xrpl/HISTORY.md]: `Added` tends to be more major stuff, so people care about it more/want to see it first

Comment (ckeshava) [reply packages/xrpl/HISTORY.md]: updated in 1e1364bca

File: packages/ripple-binary-codec/src/types/uint-64.ts [hunk 5]
```diff
@@ -12,7 +12,8 @@ function useBase10(fieldName: string): boolean {
   return (
     fieldName === 'MaximumAmount' ||
     fieldName === 'OutstandingAmount' ||
-    fieldName === 'MPTAmount'
+    fieldName === 'MPTAmount' ||
+    fieldName === 'LockedAmount'
```
Comment (khancode) [inline packages/ripple-binary-codec/src/types/uint-64.ts]: Would be cleaner to create a set of these values and check if it has the `fieldName` param.

File: packages/xrpl/HISTORY.md [hunk 6]
```diff
@@ -5,6 +5,7 @@ Subscribe to [the **xrpl-announce** mailing list](https://groups.google.com/g/xr
 ## Unreleased
 
 ### Added
+* Implement support for XLS-85d Token Escrow amendment.
```
Comment (khancode) [inline packages/xrpl/HISTORY.md]:
```suggestion
* Support for `Token Escrow` (XLS-85)
```
nit

File: packages/xrpl/src/models/transactions/escrowCreate.ts [hunk 7]
```diff
@@ -62,8 +64,10 @@ export function validateEscrowCreate(tx: Record<string, unknown>): void {
     throw new ValidationError('EscrowCreate: missing field Amount')
   }
 
-  if (typeof tx.Amount !== 'string') {
-    throw new ValidationError('EscrowCreate: Amount must be a string')
+  if (typeof tx.Amount !== 'string' && typeof tx.Amount !== 'object') {
```
Comment (achowdhry-ripple) [inline packages/xrpl/src/models/transactions/escrowCreate.ts]: nit: should this check that Amount specifically fits the object type for an IOU/MPT Amount?

File: packages/xrpl/src/models/ledger/AccountRoot.ts [hunk 8]
```diff
@@ -146,6 +146,12 @@ export interface AccountRootFlagsInterface {
    * This address can claw back issued IOUs. Once enabled, cannot be disabled.
    */
   lsfAllowTrustLineClawback?: boolean
+
+  /**
+   * If the issuer's account does not have the lsfAllowTrustLineLocking flag set,
+   * then Escrow ledger-objects cannot be created with such IOUs.
```
Comment (achowdhry-ripple) [inline packages/xrpl/src/models/ledger/AccountRoot.ts]:
```suggestion
   * Allow IOUs to be used as escrow amounts for an issuer
```

Comment (achowdhry-ripple) [reply packages/xrpl/src/models/ledger/AccountRoot.ts]: If this definition is slightly inaccurate (I'm not up to date with this spec), am open to suggestions. Existing wording just seemed a bit verbose and inconsistent with the other comment definitions

File: packages/xrpl/src/models/ledger/Escrow.ts [hunk 9]
```diff
@@ -61,4 +62,16 @@ export default interface Escrow extends BaseLedgerEntry, HasPreviousTxnID {
...
   DestinationNode?: string
+
+  /**
+   * The transfer rate or fee at which the funds are escrowed, stored at creation
+   *  and used during settlement. Applicable to both IOUs and MPTs.
+   */
+  TransferRate?: number
+
+  /**
+   * (Optional) The ledger index of the issuer's directory node associated with
```
Comment (achowdhry-ripple) [inline packages/xrpl/src/models/ledger/Escrow.ts]: nit: none of the other optional parameters have the (Optional) description. I don't mind making it clear, but if you choose to add it then could you add it to the other optional parameters for consistency?

**Comment by achowdhry-ripple** [comment]
Appreciate the cleanliness of the integration test, makes for a good code example too

File: packages/xrpl/src/models/ledger/MPTokenIssuance.ts [hunk 10]
```diff
@@ -10,4 +10,7 @@ export interface MPTokenIssuance extends BaseLedgerEntry, HasPreviousTxnID {
   TransferFee?: number
   MPTokenMetadata?: string
   OwnerNode?: string
+
+  // The total of all outstanding escrows for this issuance.
+  LockedAmount?: string
```
Comment (khancode) [inline packages/xrpl/src/models/ledger/MPTokenIssuance.ts]:
```suggestion
  LockedAmount?: string
```
To match the format.

File: packages/xrpl/src/models/ledger/MPToken.ts [hunk 11]
```diff
@@ -8,4 +8,7 @@ export interface MPToken extends BaseLedgerEntry, HasPreviousTxnID {
   MPTAmount?: MPTAmount
   Flags: number
   OwnerNode?: string
+
+  // The total of all outstanding escrows for this issuance.
+  LockedAmount?: string
```
Comment (khancode) [inline packages/xrpl/src/models/ledger/MPToken.ts]:
```suggestion
  LockedAmount?: string
```
ditto

File: packages/xrpl/src/models/transactions/escrowCreate.ts (hunk 7 above)
Comment (khancode) [reply packages/xrpl/src/models/transactions/escrowCreate.ts]: You can use `isAmount()` and `isMPTAmount()` and remove this validation check.

File: packages/xrpl/src/models/ledger/AccountRoot.ts (hunk 8 above)
Comment (ckeshava) [reply packages/xrpl/src/models/ledger/AccountRoot.ts]: Hello Ashray, I have incorporated your suggestion. It does capture the spirit of what I needed to convey.

File: packages/xrpl/src/models/ledger/Escrow.ts (hunk 9 above)
Comment (ckeshava) [reply packages/xrpl/src/models/ledger/Escrow.ts]: okay. I copied these comments verbatim from the XLS specification. I have removed the "Optional" word in this commit: 4e7c292bc..3e458b18e

File: packages/xrpl/src/models/transactions/escrowCreate.ts (hunk 7 above)
Comment (ckeshava) [reply packages/xrpl/src/models/transactions/escrowCreate.ts]: thanks. I have incorporated this suggestion in 4e7c292bc..3e458b18e

File: packages/xrpl/src/models/transactions/escrowCreate.ts [hunk 12]
```diff
@@ -62,9 +65,7 @@ export function validateEscrowCreate(tx: Record<string, unknown>): void {
     throw new ValidationError('EscrowCreate: missing field Amount')
   }
```
Comment (khancode) [inline packages/xrpl/src/models/transactions/escrowCreate.ts]: Now that you're using `validateRequiredField(tx, 'Amount', isAmount)`, you can delete this:
`
if (tx.Amount === undefined) {
    throw new ValidationError('EscrowCreate: missing field Amount')
  }
`

File: packages/xrpl/src/models/transactions/escrowCreate.ts [hunk 13]
```diff
@@ -62,9 +65,7 @@ export function validateEscrowCreate(tx: Record<string, unknown>): void {
...
 
-  if (typeof tx.Amount !== 'string') {
-    throw new ValidationError('EscrowCreate: Amount must be a string')
-  }
+  validateRequiredField(tx, 'Amount', isAmount)
 
   validateRequiredField(tx, 'Destination', isAccount)
   validateOptionalField(tx, 'DestinationTag', isNumber)
```
Comment (khancode) [inline packages/xrpl/src/models/transactions/escrowCreate.ts]:
```suggestion
  validateRequiredField(tx, 'Amount', isAmount)
  validateRequiredField(tx, 'Destination', isAccount)
  validateOptionalField(tx, 'DestinationTag', isNumber)
```
nit

File: packages/xrpl/test/integration/transactions/escrowCreate.test.ts [hunk 14]
```diff
@@ -56,4 +69,274 @@ describe('EscrowCreate', function () {
...
+  it(
+    'escrow with IOU -- validate EscrowCreate and EscrowFinish transactions',
+    async () => {
+      const wallet1 = await generateFundedWallet(testContext.client)
+      const wallet2 = await generateFundedWallet(testContext.client)
+
+      // Step-1: configure Issuer (testContext.wallet.classicAddress) to allow their IOUs to be used as escrow amounts
+      const setupAccountSetTx: AccountSet = {
+        TransactionType: 'AccountSet',
+        Account: testContext.wallet.classicAddress,
```
Comment (khancode) [inline packages/xrpl/test/integration/transactions/escrowCreate.test.ts]: Cleaner to set `testContext.wallet.classicAddress` to `issuer` variable.

File: packages/xrpl/test/integration/transactions/escrowCreate.test.ts [hunk 15]
```diff
@@ -56,4 +69,274 @@ describe('EscrowCreate', function () {
...
+      }
+
+      const txn_response = await testTransaction(
+        testContext.client,
+        tx,
+        wallet1,
+      )
+
+      // Step-5: fetch the escrow object
+      const wallet1_objects = await testContext.client.request({
```
Comment (khancode) [inline packages/xrpl/test/integration/transactions/escrowCreate.test.ts]:
```suggestion
      const wallet1Objects = await testContext.client.request({
```
snake_case is pythonic.

File: packages/xrpl/test/integration/transactions/escrowCreate.test.ts [hunk 16]
```diff
@@ -56,4 +69,274 @@ describe('EscrowCreate', function () {
...
+          currency: 'USD',
+          value: '100',
+          issuer: testContext.wallet.classicAddress,
+        },
+        Destination: wallet2.classicAddress,
+        FinishAfter: CLOSE_TIME + 2,
+        CancelAfter: CLOSE_TIME + 4,
+      }
+
+      const txn_response = await testTransaction(
```
Comment (khancode) [inline packages/xrpl/test/integration/transactions/escrowCreate.test.ts]:
```suggestion
      const txnResponse = await testTransaction(
```
ditto

File: packages/xrpl/test/integration/transactions/escrowCreate.test.ts [hunk 17]
```diff
@@ -56,4 +69,274 @@ describe('EscrowCreate', function () {
...
+      )
+
+      // Step 7.2: rippled uses the close time of the previous ledger
+      await sendLedgerAccept(testContext.client)
+
+      // Step 7.3: execute the EscrowFinish transaction
+      await testTransaction(testContext.client, escrowFinishTx, wallet1)
+
+      // Step 8: check that the escrow object has been removed
+      const wallet1_objects_after_escrow_finish =
```
Comment (khancode) [inline packages/xrpl/test/integration/transactions/escrowCreate.test.ts]:
```suggestion
      const wallet1EscrowObjects =
```
Variable is to lengthy and pythonic.

File: packages/xrpl/test/integration/transactions/escrowCreate.test.ts [hunk 18]
```diff
@@ -56,4 +69,274 @@ describe('EscrowCreate', function () {
...
+      }
+      await testTransaction(
+        testContext.client,
+        setupAccountSetTx,
+        testContext.wallet,
+      )
+
+      // Step-2: setup appropriate trust lines to transfer the IOU.
+      // This is needed for both wallet1 and wallet2 to hold the USD IOU token.
+      const setupTrustSetTx_1: TrustSet = {
```
Comment (khancode) [inline packages/xrpl/test/integration/transactions/escrowCreate.test.ts]:
```suggestion
      const setupTrustSetTx1: TrustSet = {
```

File: packages/xrpl/test/integration/transactions/escrowCreate.test.ts [hunk 19]
```diff
@@ -56,4 +69,274 @@ describe('EscrowCreate', function () {
...
+        Account: wallet1.classicAddress,
+        LimitAmount: {
+          currency: 'USD',
+          issuer: testContext.wallet.classicAddress,
+          value: '1000',
+        },
+      }
+      await testTransaction(testContext.client, setupTrustSetTx_1, wallet1)
+
+      const setupTrustSetTx_2: TrustSet = {
```
Comment (khancode) [inline packages/xrpl/test/integration/transactions/escrowCreate.test.ts]:
```suggestion
      const setupTrustSetTx2: TrustSet = {
```

File: packages/xrpl/test/integration/transactions/escrowCreate.test.ts [hunk 20]
```diff
@@ -56,4 +69,274 @@ describe('EscrowCreate', function () {
...
+          currency: 'USD',
+          value: '100',
+          issuer: testContext.wallet.classicAddress,
+        },
+        Destination: wallet2.classicAddress,
+        FinishAfter: CLOSE_TIME + 2,
+        CancelAfter: CLOSE_TIME + 4,
+      }
+
+      const txn_response = await testTransaction(
```
Comment (khancode) [inline packages/xrpl/test/integration/transactions/escrowCreate.test.ts]:
```suggestion
      const txnResponse = await testTransaction(
```

File: packages/xrpl/test/integration/transactions/escrowCreate.test.ts [hunk 21]
```diff
@@ -56,4 +69,274 @@ describe('EscrowCreate', function () {
...
+        testContext.client,
+        tx,
+        wallet1,
+      )
+
+      // Step-5: fetch the escrow object
+      const wallet1_objects = await testContext.client.request({
```
Comment (khancode) [inline packages/xrpl/test/integration/transactions/escrowCreate.test.ts]:
```suggestion
      const wallet1Objects = await testContext.client.request({
```

File: packages/xrpl/test/integration/transactions/escrowCreate.test.ts [hunk 22]
```diff
@@ -56,4 +69,274 @@ describe('EscrowCreate', function () {
     },
     TIMEOUT,
   )
+
+  it(
+    'escrow with IOU -- validate EscrowCreate and EscrowFinish transactions',
+    async () => {
+      const wallet1 = await generateFundedWallet(testContext.client)
+      const wallet2 = await generateFundedWallet(testContext.client)
```
Comment (khancode) [inline packages/xrpl/test/integration/transactions/escrowCreate.test.ts]: I would rename the wallets to specify their use in this test. For example, `wallet1` can be renamed to `escrowWallet`

File: packages/xrpl/test/integration/transactions/escrowCreate.test.ts [hunk 23]
```diff
@@ -56,4 +69,274 @@ describe('EscrowCreate', function () {
...
+      )
+
+      // Step 7.2: rippled uses the close time of the previous ledger
+      await sendLedgerAccept(testContext.client)
+
+      // Step 7.3: execute the EscrowCancel transaction
+      await testTransaction(testContext.client, escrowCancelTx, wallet1)
+
+      // Step 8: check that the escrow object has been removed
+      const wallet1_objects_after_escrow_cancel =
```
Comment (khancode) [inline packages/xrpl/test/integration/transactions/escrowCreate.test.ts]:
```suggestion
      const wallet1EscrowObjects =
```

File: packages/xrpl/src/models/transactions/escrowCreate.ts (hunk 7 above)
Comment (ckeshava) [reply packages/xrpl/src/models/transactions/escrowCreate.ts]: @khancode  `isAmount` already includes `isMPTAmount`

File: packages/xrpl/src/models/transactions/escrowCreate.ts (hunk 12 above)
Comment (ckeshava) [reply packages/xrpl/src/models/transactions/escrowCreate.ts]: incorporated your suggestion in 4279b5efb

File: packages/ripple-binary-codec/src/types/uint-64.ts (hunk 5 above)
Comment (ckeshava) [reply packages/ripple-binary-codec/src/types/uint-64.ts]: incorporated your suggestion in 4279b5efb

File: packages/xrpl/test/integration/transactions/escrowCreate.test.ts (hunk 14 above)
Comment (ckeshava) [reply packages/xrpl/test/integration/transactions/escrowCreate.test.ts]: changed variable name in 4d39b907a

File: packages/xrpl/test/integration/transactions/escrowCreate.test.ts (hunk 15 above)
Comment (ckeshava) [reply packages/xrpl/test/integration/transactions/escrowCreate.test.ts]: changed variable name in 4d39b907a

File: packages/xrpl/test/integration/transactions/escrowCreate.test.ts (hunk 16 above)
Comment (ckeshava) [reply packages/xrpl/test/integration/transactions/escrowCreate.test.ts]: changed variable name in 4d39b907a

File: packages/xrpl/test/integration/transactions/escrowCreate.test.ts (hunk 17 above)
Comment (ckeshava) [reply packages/xrpl/test/integration/transactions/escrowCreate.test.ts]: changed variable name in 4d39b907a

File: packages/xrpl/test/integration/transactions/escrowCreate.test.ts (hunk 18 above)
Comment (ckeshava) [reply packages/xrpl/test/integration/transactions/escrowCreate.test.ts]: changed variable name in 4d39b907a

File: packages/xrpl/test/integration/transactions/escrowCreate.test.ts (hunk 19 above)
Comment (ckeshava) [reply packages/xrpl/test/integration/transactions/escrowCreate.test.ts]: changed variable name in 4d39b907a

File: packages/xrpl/test/integration/transactions/escrowCreate.test.ts (hunk 20 above)
Comment (ckeshava) [reply packages/xrpl/test/integration/transactions/escrowCreate.test.ts]: changed variable name in 4d39b907a

File: packages/xrpl/test/integration/transactions/escrowCreate.test.ts (hunk 21 above)
Comment (ckeshava) [reply packages/xrpl/test/integration/transactions/escrowCreate.test.ts]: changed variable name in 4d39b907a

File: packages/xrpl/test/integration/transactions/escrowCreate.test.ts (hunk 22 above)
Comment (ckeshava) [reply packages/xrpl/test/integration/transactions/escrowCreate.test.ts]: changed variable name in 4d39b907a

File: packages/xrpl/test/integration/transactions/escrowCreate.test.ts (hunk 23 above)
Comment (ckeshava) [reply packages/xrpl/test/integration/transactions/escrowCreate.test.ts]: changed variable name in 9e8c2552b

**Comment by ckeshava** [comment]
@khancode  I have addressed your comments, please take a look

File: packages/ripple-binary-codec/src/types/uint-64.ts [hunk 24]
```diff
@@ -8,12 +8,15 @@ const HEX_REGEX = /^[a-fA-F0-9]{1,16}$/
...
 const mask = BigInt(0x00000000ffffffff)
 
+const BASE10_AMOUNT_FIELDS = new Set([
+  'MaximumAmount',
+  'OutstandingAmount',
+  'MPTAmount',
+  'LockedAmount',
+])
+
 function useBase10(fieldName: string): boolean {
```
Comment (khancode) [inline packages/ripple-binary-codec/src/types/uint-64.ts]:
```suggestion
function isBase10(fieldName: string): boolean {
```

**Review by khancode — APPROVED** [review]
Just one small thing to address and LGTM!

File: packages/ripple-binary-codec/src/types/uint-64.ts (hunk 24 above)
Comment (ckeshava) [reply packages/ripple-binary-codec/src/types/uint-64.ts]: updated in [d08d8d0](https://github.com/XRPLF/xrpl.js/pull/3027/commits/d08d8d0b8fb341c7d90732a1c46e20412bf8fb01)

**Comment by ckeshava** [comment]
thank you for the reviews.
